### ISSUE TITLE
Assertion during training after the last merges (50mr)

### ISSUE THREAD

**Issue by Belzedar94** [fairy-stockfish/variant-nnue-tools#12]
Assertion:

`Assertion failed: bits <= 6, file D:\NNUE training\Pawnsideways\lib/nnue_training_data_formats.h, line 662`

Example of command used:

`python train.py --resume-from-model startingpointfortraining.pt --threads 4 --num-workers 8 --gpus 1 --max_epochs 9 --lambda 0.8 pawnsideways_80Md5_r2e16l08.bin pawnsideways_80Md5_r2e16l08.bin`

**Comment by ianfab** [comment]
Error related to https://github.com/fairy-stockfish/variant-nnue-pytorch/issues/22.
