### ISSUE TITLE
Unexpected assertion when generating LB data

### ISSUE THREAD

**Issue by Belzedar94** [fairy-stockfish/variant-nnue-tools#3]
Documenting the issue to have it on the radar. It happens when I generate data for Shaco and Janggi

Error:

`.......................Assertion failed: 0 <= ss->ply && ss->ply < MAX_PLY, file search.cpp, line 1543`

**Comment by ianfab** [comment]
The latest commit should fix this. Binaries can be downloaded from https://github.com/ianfab/variant-nnue-tools/actions/runs/2442973051. If the error still occurs, please reopen or create a new issue.
