### ISSUE TITLE
Error generating training data using Linux system

### ISSUE THREAD

**Issue by zhaoxishm** [fairy-stockfish/variant-nnue-tools#6]
When Linux is used to generate training data, "Segmentation Fault (core DUMPED)" is displayed.

![3334](https://user-images.githubusercontent.com/14160172/171982289-6b51993d-75c7-451e-bf64-ceb26ffedcf0.png)

Test parameters used：
uci
setoption name Use NNUE value false
setoption name Threads value 8
setoption name Hash value 2048
setoption name Use NNUE value pure
setoption name EvalFile value xiangqi-6f64c55fcb28.nnue
isready
generate_training_data depth 20 count 100000 random_multi_pv 4 random_multi_pv_diff 100 random_move_count 8 random_move_max_ply 20 write_min_ply 5 eval_limit 10000 set_recommended_uci_options data_format bin output_file_name training_data.bin

**Comment by ianfab** [comment]
Thanks for the report. I moved the issue to the data generator repository (variant-nnue-tools).

Depth 20 is a quite extreme setting to generate data and would take forever to complete. Even depth 10 already is a very high depth for data generation that is rarely used. Typically used depths are in the range 2-10 depending on resources. Does the error also occur when you use a lower depth? And which binary did you use exactly?

**Comment by zhaoxishm** [comment]
Even depth 4 can have this error
I use Ubuntu 20.04 Server.  This failure occurs with any version: bmi2 or x86-64
A lot of times I set depth 5 count 1000 and it will run all night, and it's 100% CPU usage, and I don't know what's going on, there's no output log, I don't know what's going on inside the program
I would love to have log output
It would be better to have a log output, and running the training program will not work on most Linux systems (including Ubuntu 14.04 and centos 7.4) because the required version numbers of glibc.2.27 or 2.29 are too high
It would be nice if there were an official Doker container

**Comment by zhaoxishm** [comment]
uci
setoption name UCI_Variant value xiangqi
setoption name PruneAtShallowDepth value false
setoption name Use NNUE value pure
setoption name EvalFile value xiangqi-6f64c55fcb28.nnue
setoption name Threads value 8
setoption name Hash value 2048
isready
generate_training_data depth 5 count 10000 random_multi_pv 4 book fen.epd random_multi_pv_diff 100 random_move_count 8 random_move_max_ply 20 write_min_ply 5 write_max_ply 1000 eval_limit 10000 set_recommended_uci_options data_format bin output_file_name training_data.bin

This is the parameter I've been running with all night and it seems to keep running.
I don't know what's wrong, it looks like it's going on forever.
![2221](https://user-images.githubusercontent.com/14160172/172017042-40b2f234-2a48-4cbc-9777-9158e72e2ef6.jpg)

**Comment by ianfab** [comment]
This seems to be related to #3, since I get the same failed assertion when enabling `debug=yes`:
```
stockfish: search.cpp:1543: Stockfish::Value Stockfish::{anonymous}::qsearch(Stockfish::Position&, Stockfish::Search::Stack*, Stockfish::Value, Stockfish::Value, Stockfish::Depth) [with Stockfish::{anonymous}::NodeType nodeType = Stockfish::<unnamed>::NonPV; Stockfish::Depth = int]: Assertion `0 <= ss->ply && ss->ply < MAX_PLY' failed.
```

**Comment by ianfab** [comment]
The latest commit should fix this. Binaries can be downloaded from https://github.com/ianfab/variant-nnue-tools/actions/runs/2442973051. If the error still occurs, please reopen or create a new issue.
